/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'padilla' at '16/12/16 18:02' with Gradle 3.0
 *
 * @author padilla, @date 16/12/16 18:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
